app = "imgtext-api"
primary_region = "sjc"

[build]

[env]
  PORT = "8080"
  OMP_NUM_THREADS = "1"
  MKL_NUM_THREADS = "1"

[http_service]
  internal_port = 5000
  force_https = true

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
